<!DOCTYPE html>
<html>
<head>
    <title>URL Table Data</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        h2 { text-align: center; }
        .footer { margin-top: 20px; font-size: 10px; color: #777; text-align: center; }
    </style>
</head>
<body>
    <h2>Shortened URLs Report</h2>
    <p>Generated on: {{ now()->format('d M Y, H:i') }}</p>
    <table>
        <thead>
            <tr>
                <th>Short URL</th>
                <th>Long URL</th>
                <th>Hits</th>
                <th>Created On</th>
            </tr>
        </thead>
        <tbody>
            @foreach($urls as $url)
                <tr>
                    <td>{{ $url->short_url }}</td>
                    <td>{{ $url->long_url }}</td>
                    <td>{{ $url->hits }}</td>
                    <td>{{ $url->created_at->format('d M, Y') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div class="footer">
        Generated by URL Shortner System
    </div>
</body>
</html>
